### ISSUE TITLE
Синтаксис

### ISSUE THREAD

**Issue by Morfey216** [StrehaAleksandr/KeksoGram#1]
Ставим точку с запятой и логические фрагменты кода разделяем строкой
https://github.com/StrehaAleksandr/KeksoGram/blob/f9480c30b27d1007e52b33cfe4f96bf1101d1c51/scripts/main.js#L23

**Comment by StrehaAleksandr** [comment]
сделал

**Comment by Morfey216** [comment]
Поправь:
https://github.com/StrehaAleksandr/KeksoGram/blob/a56c22cdf6ea78cc221e3699c2b9ecb0d0634d38/scripts/main.js#L51
https://github.com/StrehaAleksandr/KeksoGram/blob/a56c22cdf6ea78cc221e3699c2b9ecb0d0634d38/scripts/main.js#L138

И здесь - код разделяем одной строкой
https://github.com/StrehaAleksandr/KeksoGram/blob/a56c22cdf6ea78cc221e3699c2b9ecb0d0634d38/scripts/main.js#L75-L78
https://github.com/StrehaAleksandr/KeksoGram/blob/a56c22cdf6ea78cc221e3699c2b9ecb0d0634d38/scripts/main.js#L99-L103

**Comment by StrehaAleksandr** [comment]
сделал
