### ISSUE TITLE
Нейминг обработчиков

### ISSUE THREAD

**Issue by Morfey216** [StrehaAleksandr/KeksoGram#12]
Имя функции-обработчика не соответствует требованиям (критерий Д4)
https://github.com/StrehaAleksandr/KeksoGram/blob/30bcd16716707e07db563d29773410fd0b3e47a8/scripts/upload-image.js#L259

**Comment by StrehaAleksandr** [comment]
сделал

**Comment by Morfey216** [comment]
Не, не так...
https://github.com/StrehaAleksandr/KeksoGram/blob/78587d744972295d18092b8bd0508cbed027d03b/scripts/upload-image.js#L242
Поскольку ты обрабатываешь событие `click`, то название функции-обработчика будет onUploadSubmitButton**Click**

**Comment by StrehaAleksandr** [comment]
сделал
