### ISSUE TITLE
Обработчики

### ISSUE THREAD

**Issue by Morfey216** [StrehaAleksandr/KeksoGram#13]
Определись, с каким событием ты работаешь:
https://github.com/StrehaAleksandr/KeksoGram/blob/30bcd16716707e07db563d29773410fd0b3e47a8/scripts/upload-image.js#L259
https://github.com/StrehaAleksandr/KeksoGram/blob/30bcd16716707e07db563d29773410fd0b3e47a8/scripts/upload-image.js#L268
а то получается, что снимаешь несуществующий обработчик

**Comment by StrehaAleksandr** [comment]
сделал

**Comment by Morfey216** [comment]
Здесь нужно доработать... Форма отправляется не только по клику на кнопку "Отправить" но и при нажатии клавиши Enter, поэтому, как правило, обрабатывать надо событие `submit`  на самой форме

**Comment by StrehaAleksandr** [comment]
сделал
