### ISSUE TITLE
Единообразное объявление функций

### ISSUE THREAD

**Issue by Morfey216** [StrehaAleksandr/KeksoGram#14]
Все функции создаются в едином стиле: используется либо [«функциональное выражение»](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/function), либо как [«функциональное объявление»](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function). Смешение стилей в рамках проекта не допускается (критерий Д5)

https://github.com/StrehaAleksandr/KeksoGram/blob/30bcd16716707e07db563d29773410fd0b3e47a8/scripts/upload-image.js#L68
https://github.com/StrehaAleksandr/KeksoGram/blob/30bcd16716707e07db563d29773410fd0b3e47a8/scripts/upload-image.js#L79

**Comment by StrehaAleksandr** [comment]
сделал
