### ISSUE TITLE
Оптимизация установки флага валидации хэштегов (if)

### ISSUE THREAD

**Issue by Morfey216** [StrehaAleksandr/KeksoGram#15]
Рассмотрим код:
https://github.com/StrehaAleksandr/KeksoGram/blob/30bcd16716707e07db563d29773410fd0b3e47a8/scripts/upload-image.js#L209-L212
Здесь полю `onlySharp `присваивается логическое значение. Условие внутри if тоже возвращает логическое значение. Получаем цепочку: если _истина_, то присвоить _истину_. Правильнее не писать отдельную проверку, а присвоить напрямую 
`errorsMessagesStatus.onlySharp = hashtagsArray[i].length === 1;`
А для того, чтобы случайно не перезатереть уже включенный статус ошибки в предыдущих хэштегаг (то есть учесть возможный true), используют оператор ИЛИ, который в JS работает по сокращенной системе слева-направо (читать [ЗДЕСЬ](https://learn.javascript.ru/logical-operators#ili-nahodit-pervoe-istinnoeznachenie))
В результате получишь:
`errorsMessagesStatus.onlySharp = errorsMessagesStatus.onlySharp || hashtagsArray[i].length === 1;`

**Comment by StrehaAleksandr** [comment]
сделал

**Comment by Morfey216** [comment]
эти строки относятся к одной логической структуре, их не разделяют друг от друга
https://github.com/StrehaAleksandr/KeksoGram/blob/78587d744972295d18092b8bd0508cbed027d03b/scripts/upload-image.js#L202-L208

**Comment by StrehaAleksandr** [comment]
сделал
