### ISSUE TITLE
И снова магия

### ISSUE THREAD

**Issue by Morfey216** [StrehaAleksandr/KeksoGram#16]
Вынести в константы 
https://github.com/StrehaAleksandr/KeksoGram/blob/30bcd16716707e07db563d29773410fd0b3e47a8/scripts/upload-image.js#L198
https://github.com/StrehaAleksandr/KeksoGram/blob/30bcd16716707e07db563d29773410fd0b3e47a8/scripts/upload-image.js#L214
https://github.com/StrehaAleksandr/KeksoGram/blob/30bcd16716707e07db563d29773410fd0b3e47a8/scripts/upload-image.js#L152
https://github.com/StrehaAleksandr/KeksoGram/blob/30bcd16716707e07db563d29773410fd0b3e47a8/scripts/upload-image.js#L147

**Comment by StrehaAleksandr** [comment]
сделал

**Comment by Morfey216** [comment]
Если я прописываю ошибки, то нужно пройтись по всему коду и перепроверить )
https://github.com/StrehaAleksandr/KeksoGram/blob/78587d744972295d18092b8bd0508cbed027d03b/scripts/upload-image.js#L156

**Comment by StrehaAleksandr** [comment]
сделал
