### ISSUE TITLE
Принцип DRY

### ISSUE THREAD

**Issue by Morfey216** [StrehaAleksandr/KeksoGram#3]
Эти участки кода повторяются постоянно:
https://github.com/StrehaAleksandr/KeksoGram/blob/f9480c30b27d1007e52b33cfe4f96bf1101d1c51/scripts/main.js#L48-L50

Необходимо убрать повторения кода. У тебя два варианта: решить вопрос с генератором случайных чисел, чтобы не выдавал правую границу, либо вынести код в функцию

**Comment by StrehaAleksandr** [comment]
сделал
