### ISSUE TITLE
Работа с template

### ISSUE THREAD

**Issue by Morfey216** [StrehaAleksandr/KeksoGram#5]
У тебя не совсем правильно построена работа с шаблоном... Давай посмотрим твой код
https://github.com/StrehaAleksandr/KeksoGram/blob/a56c22cdf6ea78cc221e3699c2b9ecb0d0634d38/scripts/main.js#L47
Здесь ты получил из разметки `<template>`, который сам по себе тебе для работы не нужен. Если вывести его в консоль, то увидим, что его прямым содержимым является `#document-fragment`, работать с которым нет никакого смысла.

Далее - здесь ты делаешь клонирование контента. 
https://github.com/StrehaAleksandr/KeksoGram/blob/a56c22cdf6ea78cc221e3699c2b9ecb0d0634d38/scripts/main.js#L78
Опять же, если заглянуть в консоль, то увидим, что на самом деле ты клонируешь как раз тот самый `#document-fragment`. Именно поэтому тебе приходится внутри этого фрагмента искать нужный элемент
https://github.com/StrehaAleksandr/KeksoGram/blob/a56c22cdf6ea78cc221e3699c2b9ecb0d0634d38/scripts/main.js#L79

Зная эту цепочку, логически правильнее поступить следующим образом: 
1. сразу получить из разметки код нужной тебе структуры изображения
2. при создании новой картинки клонировать не фрагмент, а эту структуру
На практике это выглядит так:
```
var template = document.querySelector('#picture').content.querySelector('.picture');
...
var image = template.cloneNode(true);
```

**Comment by StrehaAleksandr** [comment]
сделал
