### ISSUE TITLE
Избыточные переменные

### ISSUE THREAD

**Issue by Morfey216** [StrehaAleksandr/KeksoGram#6]
В данном фрагменте кода промежуточные переменные не нужны. Более того - они засоряют память.
https://github.com/StrehaAleksandr/KeksoGram/blob/a56c22cdf6ea78cc221e3699c2b9ecb0d0634d38/scripts/main.js#L79-L85

С учетом рекомендаций здесь https://github.com/StrehaAleksandr/KeksoGram/issues/5#issue-1228556076
код можно упростить:
```
image.querySelector('.picture__img').src = allImage[i].url;
image.querySelector('.picture__likes').textContent = allImage[i].likes;
image.querySelector('.picture__comments').textContent = allImage[i].comments.length;
```

Тот же подход можно применить и здесь:
https://github.com/StrehaAleksandr/KeksoGram/blob/a56c22cdf6ea78cc221e3699c2b9ecb0d0634d38/scripts/main.js#L128-L131

**Comment by StrehaAleksandr** [comment]
сделал
