### ISSUE TITLE
Разделение кода по функционалу

### ISSUE THREAD

**Issue by Morfey216** [StrehaAleksandr/KeksoGram#7]
Код должен быть логически стройным и понятным - каждый блок отвечает за свой участок работы.
https://github.com/StrehaAleksandr/KeksoGram/blob/a56c22cdf6ea78cc221e3699c2b9ecb0d0634d38/scripts/main.js#L69-L88
В этом цикле ты смешал логически абсолютно разные вещи: генерацию данных и отображение изображений.
Код нужно разделить. Создай функцию отрисовки изображений, внутри которой и выполняй всю работу по генерации разметки изображений на основе ранее полученных данных.

**Comment by StrehaAleksandr** [comment]
сделал
