### ISSUE TITLE
Множественные DOM-операции

### ISSUE THREAD

**Issue by Morfey216** [StrehaAleksandr/KeksoGram#8]
Критерий Б26 говорит следующее: "Множественные DOM-операции производятся на элементах, которые не добавлены в DOM"
Это означает, что добавление изображений на страницу (и комментариев при просмотре большого изображения) нужно делать за один прием. Реализуется через `DocumentFragment`. Почитать можно здесь: https://habr.com/ru/post/413287/

**Comment by StrehaAleksandr** [comment]
сделал
