### ISSUE TITLE
Ограничение количества комментариев

### ISSUE THREAD

**Issue by Morfey216** [StrehaAleksandr/KeksoGram#9]
http://joxi.ru/E2p4OR1Tvby7Q2
Сразу после открытия изображения в полноэкранном режиме должно отображаться не более 5 комментариев. Пункт 4.5 ТЗ

П.С. Загляни в критерий Б24, там есть хорошая подсказка по способу реализации...

**Comment by StrehaAleksandr** [comment]
сделал
